[workspace.package]
version = "0.1.0"
authors = ["Alina-sul"]
edition = "2021"


[package]
name = "book-notes"
version.workspace = true
edition.workspace = true
authors.workspace = true

[workspace]
members = [
    ".",
    "crates/api",
]

[workspace.dependencies]
book_notes_api = {path = "./crates/api"}

[dependencies]
tokio = { version = "1", features = ["full"] }  # Async runtime
book_notes_api = { workspace = true}
actix-web = "4.9.0"