[workspace.package]
version = "0.1.0"
authors = ["Alina-sul"]
edition = "2021"


[package]
name = "book-notes"
version.workspace = true
edition.workspace = true
authors.workspace = true

[workspace]
members = [
    ".",
    "crates/api",
]

[workspace.dependencies]
book_notes_api = {path = "./crates/api"}

[dependencies]
axum = { version = "0.7", features = ["tokio", "http1"] }
tokio = { version = "1", features = ["full"] }  # Async runtime
book_notes_api = { workspace = true}
sqlx = "0.8.2"
# For loading environment variables:
dotenvy = "0.15"