# Rust formatting configuration (stable features only)

# Indentation and line length
max_width = 100
hard_tabs = false
tab_spaces = 4

# Imports
reorder_imports = true

# Function formatting
fn_params_layout = "Tall"

# Misc
use_small_heuristics = "Default"